on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
  push:
    branches:
      - main
jobs:
  print:
    name: Print for testing purposes
    runs-on: ubuntu-20.04
    steps:
      - name: Set AWS Account
        id: set-account
        run: |
          echo "version"