name: Maven Version on release
concurrency: "maven-version"
on:
  push:
    branches:
      - main
    paths:
      - '**'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Merged PR Labels
        id: pr
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Version
        id: version
        run: |
          echo "${{ steps.pr.outputs.labels }}"
          git config --global user.name 'ajbuckley'
          git config --global user.email 'dbuckley@users.noreply.github.com'
          git pull --rebase=false origin main
          
          ./version.sh "${{ steps.pr.outputs.labels }}"
          git add -A
          git commit -m "Bumping version for release [skip actions]"
          git push
        working-directory: ./
      - name: Get version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=version::$VERSION"
        id: get_version
      - name: Print version
        run: | 
          echo "${{ steps.get_version.outputs.version }}"