name: Maven Version on release
concurrency: "maven-version"
on:
  pull_request:
    types: [ labeled ]
jobs:
  build:
    runs-on: ubuntu-20.04
    if: contains(github.event.label.name, 'release')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Version
        id: version
        run: |
          echo "${{ github.event.label.name }}"
          git config --global user.name 'ajbuckley'
          git config --global user.email 'dbuckley@users.noreply.github.com'
          git pull --rebase=false origin ${{ github.head_ref }}
          
          ./version.sh "${{ github.event.label.name }}"
          git add -A
          git commit -m "Bumping version for release [skip actions]"
          git push
        working-directory: ./